version: "3.0"

services:
 wordpress:
  image: wordpress:5.7.2-php7.4-apache
  restart: unless-stopped
  ports:
   - "8080:80"
  volumes:
   - miword:/var/lib/html

  environment:
   WORDPRESS_DB_HOST: db
   WORDPRESS_DB_USER: wordpress
   WORDPRESS_DB_NAME: miBBDD
   WORDPRESS_DB_PASSWORD: 12345

 db:
  image: mariadb:10.6.3-focal
  restart: unless-stopped
  volumes:
   - mariadb:/var/lib/mysql

  environment: 
   MYSQL_ROOT_PASSWORD: 1234
   MYSQL_DATABASE: miBBDD
   MYSQL_USER: wordpress
   MYSQL_PASSWORD: 12345

 phpmyadmin:
  image: phpmyadmin:5.1.1-apache
  restart: unless-stopped
  ports:
    - "8000:80"

  environment:
    PMA_HOST: db
    

volumes:
 mariadb:
 miword:
